CREATE TABLE user_roles(

    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
)



CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id NUMBER DEFAULT 4, 
    status VARCHAR(255) DEFAULT 'pending' CHECK (status in ('active', 'pending', 'removed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES user_roles(id)
)

CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    description CLOB NOT NULL,
    image VARCHAR(255) UNIQUE NOT NULL,
    categories_id NUMBER,
    likes NUMBER DEFAULT 0,
    author VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT 'pending' CHECK (status in ('published', 'pending')),
    featured NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author) REFERENCES users (username),
    FOREIGN KEY (categories_id) REFERENCES categories (id)
)

INSERT INTO categories (name) VALUES ('Travel and Nature');






SELECT * FROM users;
SELECT * FROM user_roles;
SELECT * FROM posts;

SELECT * FROM categories;

SELECT p.id, p.title, p.image, c.name AS categories, p.author, p.created_at FROM 
posts p JOIN categories c ON p.categories_id = c.id;


ALTER TABLE users 
ADD image VARCHAR2(255);

SELECT * FROM (
    SELECT p.id, p.title, p.image, c.name AS categories, p.author, p.created_at, 
    ROW_NUMBER() OVER (ORDER BY p.created_at DESC) AS row_number
    FROM posts p JOIN categories c 
    ON p.categories_id = c.id 
    WHERE p.status = 'published' 
    )
WHERE row_number BETWEEN 1 AND 3;

SELECT COUNT(*) AS total_posts FROM posts WHERE status = 'published';

SELECT * FROM (
    SELECT p.id, p.title, p.image, p.likes, c.name AS categories, p.author, p.created_at, p.status,
    ROW_NUMBER() OVER (ORDER BY p.created_at DESC) AS row_number
    FROM posts p JOIN categories c 
    ON p.categories_id = c.id 
    WHERE p.author = 'zaydhasnain'
    )
WHERE row_number <= 3;


SELECT 
    SUM(likes) AS total_likes,
    COUNT( CASE WHEN status = 'published' THEN 1 END) AS published_post,
    COUNT( CASE WHEN status = 'pending' THEN 1 END) AS pending_post,
    COUNT( CASE WHEN featured = 1 THEN 1 END) AS featured_post
FROM posts
WHERE author = 'zaydhasnain';





COMMIT;





SELECT * FROM posts WHERE author = 'author1';

